events {}

http {
    server {
        listen 10000;

        location / {
            root /var/www/hls;
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
        }
    }
}
